import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

def generate_certificate(
    target_path: str,
    name: str,
    level: int,
    score: int,
    result: str,
    unique_id: str,
    date: str
):
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    c = canvas.Canvas(target_path, pagesize=A4)
    width, height = A4

    # Border
    margin = 15 * mm
    c.setStrokeColor(colors.HexColor("#333333"))
    c.setLineWidth(3)
    c.rect(margin, margin, width - 2*margin, height - 2*margin)

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 60, "Skill Assessment Certificate")

    # Body
    c.setFont("Helvetica", 12)
    text_y = height - 120
    line_gap = 22

    lines = [
        f"This is to certify that: {name}",
        f"Skill Level: {level}",
        f"Score: {score}/10",
        f"Result: {result}",
        f"Unique ID: {unique_id}",
        f"Date: {date}"
    ]
    for line in lines:
        c.drawCentredString(width/2, text_y, line)
        text_y -= line_gap

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width/2, 40, "Generated by Skill Evaluation System")

    c.showPage()
    c.save()
    return target_path
